using Courier.Core.Collections;

namespace Courier.Scanner;

/// <summary>
/// What a scan produced, including everything it could not work out.
/// </summary>
/// <remarks>
/// REQUIREMENTS 9 names the failure mode this type exists to prevent: "Roslyn scanning is a long
/// tail — every codebase has a pattern that breaks it. Fail visibly per endpoint, never silently.
/// An endpoint that can't be derived is listed as unresolved, not omitted."
///
/// So <see cref="Unresolved"/> is not an error channel. It is part of the result, it is rendered on
/// the sync screen next to the endpoints that did resolve, and a scan that produces some of both is
/// a success.
/// </remarks>
public sealed record ScanResult
{
    public required IReadOnlyList<ScannedEndpoint> Endpoints { get; init; }

    public required IReadOnlyList<UnresolvedEndpoint> Unresolved { get; init; }

    /// <summary>Base URLs derived from launchSettings.json and appsettings.*.json. SCAN-07.</summary>
    public IReadOnlyList<DerivedEnvironment> Environments { get; init; } = [];

    /// <summary>Which tier produced this. SCAN-08: syntax works without a restore; semantic needs one.</summary>
    public required ScanTier Tier { get; init; }

    /// <summary>Content hashes per file, for the incremental rescan. SCAN-10.</summary>
    public IReadOnlyDictionary<string, string> FileHashes { get; init; } =
        new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);

    public TimeSpan Elapsed { get; init; }

    /// <summary>
    /// Why the semantic tier was not used, when it was asked for and did not load. Shown to the
    /// user rather than swallowed: "couldn't restore" is actionable, silence is not.
    /// </summary>
    public string? SemanticUnavailableReason { get; init; }

    public int Total => Endpoints.Count + Unresolved.Count;
}

public enum ScanTier
{
    /// <summary>Parse-only. No restore, no build, works on a folder that does not compile.</summary>
    Syntax,

    /// <summary>MSBuildWorkspace loaded. Adds DTO graph walking and cross-project resolution.</summary>
    Semantic,
}

/// <param name="SourceFile">Absolute path, for the incremental hash and for "go to definition".</param>
/// <param name="DeclaringType">Fully qualified controller type, or the group for a minimal API.</param>
public sealed record ScannedEndpoint(
    string Id,
    string Method,
    string RouteTemplate,
    string DeclaringType,
    string ActionName,
    string SourceFile,
    int Line)
{
    public IReadOnlyList<ScannedParameter> Parameters { get; init; } = [];

    /// <summary>Sample body, generated by walking the DTO type graph. SCAN-04.</summary>
    public string? SampleBody { get; init; }

    public string? BodyContentType { get; init; }

    /// <summary>Declared response types per status code, for assertion generation. SCAN-05.</summary>
    public IReadOnlyList<DeclaredResponse> Responses { get; init; } = [];

    /// <summary>Policies, roles, or anonymous. SCAN-06.</summary>
    public EndpointAuthorization Authorization { get; init; } = EndpointAuthorization.Inherited;

    /// <summary>Scopes surfaced on the request before it is sent. SCAN-06.</summary>
    public IReadOnlyList<string> RequiredScopes { get; init; } = [];

    /// <summary>Notes about what could not be fully derived on an endpoint that otherwise resolved.</summary>
    public IReadOnlyList<string> PartialResolutionNotes { get; init; } = [];

    public string? Summary { get; init; }

    /// <summary>Projects into the collection model, ready to be joined with the user's overlay.</summary>
    public RequestDefinition ToRequest(string? baseUrlVariable = "baseUrl")
    {
        var request = new RequestDefinition
        {
            Id = Id,
            Name = $"{Method} /{RouteTemplate}",
            Method = Method,
            Url = $"{{{{{baseUrlVariable}}}}}/{RouteTemplate}",
            Provenance = Provenance.Generated,
            Folder = FolderFor(DeclaringType),
            Description = Summary,
            RequiredScopes = [.. RequiredScopes],
            UnresolvedNotes = [.. PartialResolutionNotes],
        };

        foreach (var parameter in Parameters)
        {
            switch (parameter.Source)
            {
                case ParameterSource.Route:
                    // Deliberately blank rather than an invented value. A route parameter is part
                    // of the URL, so a made-up "string" silently becomes /orders/string/cancel —
                    // a request to an endpoint that does not exist, which reads as a Courier bug
                    // rather than as a value the user has to supply. Left empty, the URL keeps its
                    // {id} token and the gap is visible.
                    request.PathParams[parameter.Name] = string.Empty;
                    break;

                case ParameterSource.Query:
                    request.Query.Add(new QueryParameter(
                        parameter.Name,
                        parameter.SampleValue ?? string.Empty,
                        Enabled: parameter.IsRequired,
                        parameter.TypeName));
                    break;

                case ParameterSource.Header:
                    request.Headers.Add(new HeaderValue(
                        parameter.Name,
                        parameter.SampleValue ?? string.Empty,
                        Enabled: parameter.IsRequired,
                        parameter.TypeName));
                    break;
            }
        }

        if (SampleBody is not null)
        {
            request.Body = new RequestBody
            {
                Kind = BodyKind.Json,
                Text = SampleBody,
                ContentType = BodyContentType,
            };
        }

        // SCAN-05: a declared 200 becomes a status assertion the user did not have to write.
        foreach (var response in Responses.Where(r => r.StatusCode is >= 200 and < 300))
        {
            request.Assertions.Add(new AssertionDefinition(
                AssertionKind.Status,
                Expected: response.StatusCode.ToString(),
                Source: AssertionSource.GeneratedFromContract,
                Note: response.TypeName is null ? null : $"declared to return {response.TypeName}"));

            break;
        }

        return request;
    }

    /// <summary>Groups by controller, so the tree mirrors the code's own structure.</summary>
    private static string FolderFor(string declaringType)
    {
        var name = declaringType[(declaringType.LastIndexOf('.') + 1)..];
        return name.EndsWith("Controller", StringComparison.Ordinal)
            ? name[..^"Controller".Length]
            : name;
    }
}

/// <param name="Reason">Plain English, shown on the sync screen. Never a stack trace.</param>
public sealed record UnresolvedEndpoint(
    string DeclaringType,
    string ActionName,
    string SourceFile,
    int Line,
    string Reason);

/// <param name="SampleValue">Valid by construction: honours validation attributes, enums and nullability.</param>
public sealed record ScannedParameter(
    string Name,
    ParameterSource Source,
    string TypeName,
    bool IsRequired,
    string? SampleValue);

/// <summary>Where a parameter is bound from. SCAN-03.</summary>
public enum ParameterSource
{
    Route,
    Query,
    Header,
    Body,
    Form,
    /// <summary>Injected service or similar. Not part of the request.</summary>
    Services,
    Unknown,
}

public sealed record DeclaredResponse(int StatusCode, string? TypeName);

/// <param name="Policies">Named authorization policies the endpoint requires.</param>
public sealed record EndpointAuthorization(bool AllowsAnonymous, bool RequiresAuthorization, IReadOnlyList<string> Policies, IReadOnlyList<string> Roles)
{
    public static readonly EndpointAuthorization Inherited = new(false, false, [], []);

    public static readonly EndpointAuthorization Anonymous = new(true, false, [], []);

    /// <summary>What the request pane shows before the send. SCAN-06.</summary>
    public string Describe() => (AllowsAnonymous, RequiresAuthorization, Policies.Count, Roles.Count) switch
    {
        (true, _, _, _) => "anonymous",
        (_, _, > 0, _) => $"requires {string.Join(", ", Policies)}",
        (_, _, _, > 0) => $"roles {string.Join(", ", Roles)}",
        (_, true, _, _) => "requires authentication",
        _ => "inherited",
    };
}

/// <param name="Source">Which file this came from, so the user can see why the URL is what it is.</param>
public sealed record DerivedEnvironment(string Name, string BaseUrl, string Source);
